version: "3"
services:
  db:
    image: "mongo:latest"
    container_name: "mongo"
    ports:
      - "27017:27017"

  backend:
    image: "backend"
    container_name: "backend"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    image: "frontend"
    container_name: "frontend"
    ports:
      - "80:80"
    depends_on:
      - backend
    stdin_open: true
