api:
  key: 1f29c2ffeeee6d558a3614f7eec79766
  fetchLimit: 10

spring:
  profiles:
    active: local
---
spring:
  profiles: local
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: localadmin
      database: admin
    mongo.repositories.enabled: true
